// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using urlshortenerbackend.Data;

#nullable disable

namespace urlshortenerbackend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("urlshortenerbackend.Models.ClickLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .HasColumnType("text");

                    b.Property<int?>("DeviceType")
                        .HasColumnType("integer");

                    b.Property<long>("LinkId")
                        .HasColumnType("bigint");

                    b.Property<string>("Referrer")
                        .HasColumnType("text");

                    b.Property<int?>("Source")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("LinkId");

                    b.ToTable("ClickLog");
                });

            modelBuilder.Entity("urlshortenerbackend.Models.Folder", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Folders");
                });

            modelBuilder.Entity("urlshortenerbackend.Models.Link", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("DestinationUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("FolderId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("ShortUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FolderId");

                    b.HasIndex("ShortUrl")
                        .IsUnique();

                    b.ToTable("Links");
                });

            modelBuilder.Entity("urlshortenerbackend.Models.ClickLog", b =>
                {
                    b.HasOne("urlshortenerbackend.Models.Link", "Link")
                        .WithMany("ClickLogs")
                        .HasForeignKey("LinkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Link");
                });

            modelBuilder.Entity("urlshortenerbackend.Models.Link", b =>
                {
                    b.HasOne("urlshortenerbackend.Models.Folder", "Folder")
                        .WithMany("Links")
                        .HasForeignKey("FolderId");

                    b.Navigation("Folder");
                });

            modelBuilder.Entity("urlshortenerbackend.Models.Folder", b =>
                {
                    b.Navigation("Links");
                });

            modelBuilder.Entity("urlshortenerbackend.Models.Link", b =>
                {
                    b.Navigation("ClickLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
